# Generated by Django 4.1.6 on 2023-03-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_posteo_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteo',
            old_name='subTitulo',
            new_name='subtitulo',
        ),
    ]
