# Generated by Django 4.1.6 on 2023-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_subtitulo_posteo_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='post',
            field=models.CharField(max_length=2000),
        ),
    ]
